# Site settings
title: Bookmarks
email: yu@lijiayu.net
description: my online bookmarks
baseurl: "/bookmarks" # the subpath of your site, e.g. /blog/
url: "https://yulijia.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
paginate: 5

plugins: [jekyll-paginate]
