# Site settings
title: Bookmarks
email: yu@lijiayu.net
description: > # this means to ignore newlines until "baseurl:"
my online bookmarks
baseurl: "/bookmarks" # the subpath of your site, e.g. /blog/
url: "http://yulijia.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
paginate: 5
